"""initial schema

Revision ID: 05f3334fbe04
Revises: 
Create Date: 2026-08-07 04:22:42.534671

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Available to every migration: models use app.infrastructure.db.types.UtcDateTime.
import app.infrastructure.db.types


revision: str = '05f3334fbe04'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=False),
    sa.Column('setting', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('speech_style', sa.Text(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_world_id'), ['world_id'], unique=False)

    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('player_description', sa.Text(), nullable=False),
    sa.Column('current_location', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_world_id'), ['world_id'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_game_events_session_turn', ['session_id', 'turn_index'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_memories_importance_range'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_memories_session_importance', ['session_id', 'importance', 'created_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('speaker_character_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_messages_session_turn', ['session_id', 'turn_index'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('affection', sa.Integer(), nullable=False),
    sa.Column('respect', sa.Integer(), nullable=False),
    sa.Column('fear', sa.Integer(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('trust BETWEEN -100 AND 100 AND affection BETWEEN -100 AND 100 AND respect BETWEEN -100 AND 100 AND fear BETWEEN -100 AND 100', name='ck_relationships_axis_range'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'character_id', name='uq_relationship_session_character')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_session_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_character_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_turn')
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))

    op.drop_table('messages')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memories_session_importance')
        batch_op.drop_index(batch_op.f('ix_memories_session_id'))
        batch_op.drop_index(batch_op.f('ix_memories_character_id'))

    op.drop_table('memories')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index('ix_game_events_session_turn')
        batch_op.drop_index(batch_op.f('ix_game_events_session_id'))

    op.drop_table('game_events')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_world_id'))

    op.drop_table('game_sessions')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_world_id'))

    op.drop_table('characters')
    op.drop_table('worlds')
    # ### end Alembic commands ###
