"""world state locations v1

Five new tables and nothing else. No column is added to an existing table and no row
is rewritten, so every world and session that exists keeps working -- with an empty
spatial graph, which is a valid state and the one they were already in.

No geography is invented here. A migration that seeded a starting world would be
putting canon into every existing save that nobody authored, and there is no way to
tell afterwards which places were chosen and which were manufactured by an upgrade.

Table order matters: `location_definitions` first because everything references it,
then connections, then the two per-session state tables. The downgrade reverses that.

Revision ID: 1ac0ee566568
Revises: 962dcb7cf8cf
Create Date: 2026-08-09 05:49:51.696456

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Available to every migration: models use app.infrastructure.db.types.UtcDateTime.
import app.infrastructure.db.types


revision: str = '1ac0ee566568'
down_revision: str | None = '962dcb7cf8cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('origin_session_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=60), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('parent_location_id', sa.Uuid(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('spatial_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_location_definitions_importance'),
    sa.CheckConstraint('parent_location_id IS NULL OR parent_location_id <> id', name='ck_location_definitions_not_self_parent'),
    sa.ForeignKeyConstraint(['origin_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['location_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_location_definitions_parent', ['parent_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_definitions_world_id'), ['world_id'], unique=False)
        batch_op.create_index('ix_location_definitions_world_origin', ['world_id', 'origin_session_id'], unique=False)

    op.create_table('location_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('origin_session_id', sa.Uuid(), nullable=True),
    sa.Column('from_location_id', sa.Uuid(), nullable=False),
    sa.Column('to_location_id', sa.Uuid(), nullable=False),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=60), nullable=True),
    sa.Column('distance_value', sa.Float(), nullable=True),
    sa.Column('distance_unit', sa.String(length=20), nullable=True),
    sa.Column('base_travel_minutes', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('base_travel_minutes IS NULL OR base_travel_minutes >= 0', name='ck_location_connections_travel_nonnegative'),
    sa.CheckConstraint('from_location_id <> to_location_id', name='ck_location_connections_distinct_ends'),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_location_connections_importance'),
    sa.ForeignKeyConstraint(['from_location_id'], ['location_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['location_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_connections', schema=None) as batch_op:
        batch_op.create_index('ix_location_connections_from', ['from_location_id'], unique=False)
        batch_op.create_index('ix_location_connections_to', ['to_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_connections_world_id'), ['world_id'], unique=False)
        batch_op.create_index('ix_location_connections_world_origin', ['world_id', 'origin_session_id'], unique=False)

    op.create_table('location_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('accessibility', sa.String(length=20), nullable=False),
    sa.Column('security_level', sa.Integer(), nullable=False),
    sa.Column('local_danger_modifier', sa.Integer(), nullable=False),
    sa.Column('owner_entity_id', sa.Uuid(), nullable=True),
    sa.Column('controller_entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('local_danger_modifier BETWEEN -100 AND 100', name='ck_location_states_danger_range'),
    sa.CheckConstraint('security_level BETWEEN 0 AND 100', name='ck_location_states_security_range'),
    sa.ForeignKeyConstraint(['location_id'], ['location_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'location_id', name='uq_location_states_session_location')
    )
    with op.batch_alter_table('location_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_states_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_states_session_id'), ['session_id'], unique=False)

    op.create_table('location_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_location_zones_importance'),
    sa.ForeignKeyConstraint(['location_id'], ['location_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'name', name='uq_location_zones_name')
    )
    with op.batch_alter_table('location_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_zones_location_id'), ['location_id'], unique=False)

    op.create_table('location_connection_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('accessibility', sa.String(length=20), nullable=False),
    sa.Column('traversal_modifier', sa.Integer(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('traversal_modifier BETWEEN -100 AND 100', name='ck_connection_states_modifier_range'),
    sa.ForeignKeyConstraint(['connection_id'], ['location_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'connection_id', name='uq_connection_states_session_connection')
    )
    with op.batch_alter_table('location_connection_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_connection_states_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_connection_states_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_connection_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_connection_states_session_id'))
        batch_op.drop_index(batch_op.f('ix_location_connection_states_connection_id'))

    op.drop_table('location_connection_states')
    with op.batch_alter_table('location_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_zones_location_id'))

    op.drop_table('location_zones')
    with op.batch_alter_table('location_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_states_session_id'))
        batch_op.drop_index(batch_op.f('ix_location_states_location_id'))

    op.drop_table('location_states')
    with op.batch_alter_table('location_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_location_connections_world_origin')
        batch_op.drop_index(batch_op.f('ix_location_connections_world_id'))
        batch_op.drop_index('ix_location_connections_to')
        batch_op.drop_index('ix_location_connections_from')

    op.drop_table('location_connections')
    with op.batch_alter_table('location_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_location_definitions_world_origin')
        batch_op.drop_index(batch_op.f('ix_location_definitions_world_id'))
        batch_op.drop_index('ix_location_definitions_parent')

    op.drop_table('location_definitions')
    # ### end Alembic commands ###
