"""WorldState Situations V1: ongoing processes, and who is in them.

Revision ID: f429e3bc3d11
Revises: 1ac0ee566568
Create Date: 2026-08-09 17:38:41.214322

Two new tables, plus one column on `worlds` for the processes a world already has
under way before anyone plays it -- the same relationship `initial_facts` has to
`world_facts`. No data is rewritten and no backfill is needed: an existing world starts
nothing, and a session with no situations is a session where nothing is currently under
way, which is correct for every session that existed before this ran and for most
sessions afterwards.

# Nothing is invented here

No demo war, no starting fire, no seeded festival. A migration that created situations
would be a migration that wrote fiction into every existing save -- and the world it
wrote would be one nobody chose. Worlds seed their own starting processes through the
application, the same way they seed facts and geography.

# The cycle rule is not here

`ck_situations_not_self_parent` catches the one-node case. Cycles through two or more
rows are not expressible as a CHECK constraint in SQLite or PostgreSQL, so that rule
lives in `world_situations.hierarchy.check_parent_situation` and runs before every
write that sets the link. Recorded here so a reader of the schema does not conclude the
invariant is missing.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Available to every migration: models use app.infrastructure.db.types.UtcDateTime.
import app.infrastructure.db.types


revision: str = 'f429e3bc3d11'
down_revision: str | None = '1ac0ee566568'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `server_default='[]'` so the column is NOT NULL for rows that already exist. The
    # ORM default handles new rows; without this an existing world would violate the
    # constraint the moment the column is added.
    with op.batch_alter_table("worlds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("initial_situations", sa.JSON(), nullable=False, server_default="[]")
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('threat', sa.Integer(), nullable=False),
    sa.Column('momentum', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('primary_location_id', sa.Uuid(), nullable=True),
    sa.Column('parent_situation_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('last_progressed_at', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at', sa.BigInteger(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('situation_metadata', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_situations_importance_range'),
    sa.CheckConstraint('intensity BETWEEN 0 AND 100', name='ck_situations_intensity_range'),
    sa.CheckConstraint('last_progressed_at >= started_at', name='ck_situations_progress_after_start'),
    sa.CheckConstraint('momentum BETWEEN -100 AND 100', name='ck_situations_momentum_range'),
    sa.CheckConstraint('parent_situation_id IS NULL OR parent_situation_id <> id', name='ck_situations_not_self_parent'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= started_at', name='ck_situations_resolved_after_start'),
    sa.CheckConstraint('started_at >= 0', name='ck_situations_started_at_nonnegative'),
    sa.CheckConstraint('threat BETWEEN 0 AND 100', name='ck_situations_threat_range'),
    sa.ForeignKeyConstraint(['parent_situation_id'], ['situations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_location_id'], ['location_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['game_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('situations', schema=None) as batch_op:
        batch_op.create_index('ix_situations_parent', ['parent_situation_id'], unique=False)
        batch_op.create_index('ix_situations_session_category', ['session_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_situations_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_situations_session_location', ['session_id', 'primary_location_id'], unique=False)
        batch_op.create_index('ix_situations_session_status', ['session_id', 'status'], unique=False)

    op.create_table('situation_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('situation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.infrastructure.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('situation_id', 'entity_type', 'entity_id', 'role', name='uq_situation_participants_entity_role')
    )
    with op.batch_alter_table('situation_participants', schema=None) as batch_op:
        batch_op.create_index('ix_situation_participants_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_situation_participants_situation_id'), ['situation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('situation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_situation_participants_situation_id'))
        batch_op.drop_index('ix_situation_participants_entity')

    op.drop_table('situation_participants')
    with op.batch_alter_table('situations', schema=None) as batch_op:
        batch_op.drop_index('ix_situations_session_status')
        batch_op.drop_index('ix_situations_session_location')
        batch_op.drop_index(batch_op.f('ix_situations_session_id'))
        batch_op.drop_index('ix_situations_session_category')
        batch_op.drop_index('ix_situations_parent')

    op.drop_table('situations')
    # ### end Alembic commands ###

    with op.batch_alter_table("worlds", schema=None) as batch_op:
        batch_op.drop_column("initial_situations")
